version: 35
jobs:
- name: express-react ci
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !GenerateChecksumStep
    name: generate package checksum
    files: package-lock.json
    targetFile: checksum
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetupCacheStep
    name: set up npm cache
    key: node_modules_@file:checksum@
    loadKeys:
    - node_modules
    paths:
    - node_modules
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: set build version
    buildVersion: '@script:builtin:node:determine-project-version@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build & test
    runInContainer: true
    image: node
    interpreter: !DefaultInterpreter
      commands: "# If any command in the script fails, the script will stop executing further commands\nset -e\n\napt update\n# apt install -y jq\n\n# npm clean install\nnpm ci\nexport CI=true\n\n# start server at server/index.js\nnpm start\n\nnpm test\nnpM echo \"Error: no test specified\" && exit 1\n\n# start client at client/ \nnpm run build\n\n# parse and store package version into a file which \n# will be used later to tag docker image\n# jq -r '.version' package.json > version.txt\n"
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Push to Github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/mgajdo/express-react
    passwordSecret: github-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Pull from Github
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/mgajdo/express-react
    refs: refs/heads/main
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
